@startuml Continue Analysis


participant "Service" as S
participant "Lock Service" as LS
participant "Store Service" as STS
participant "Storage Service" as SGS

database "Session Storage" as SSG
database "Local Storage" as LSG

S -> SGS: deleteSessionId()
SGS -> SSG: deleteSessionId()
S -> SGS: deletePendingAnalysis(sessionId)
SGS -> LSG: deletePendingAnalysis(sessionId)
S -> LS: unlockAnalysis(sessionId)
S -> STS: resetAnalysisState()

@enduml