@startuml Continue Analysis

participant "Facade" as F
participant "Orchestrator" as O
participant "Lock Service" as L
participant "Notification Service" as N
participant "History Service" as H
participant "Analysis Results Service" as ARS
participant "Store Service" as ST
participant "Storage Service" as STG
participant "Web Socket Service" as WS
participant "Server" as SRV

loop Until closed
    SRV -> WS: progress
    WS -> ST: progress.set(...)
    ST -> F: emit(progress)
end

alt Analysis Successful
    SRV -> WS: result
    WS -> ST: result.set(analysisId)
    ST -> O: emit(result)
    O -> N: sendNotificationSuccess()
    O -> O: constructAnalysisHistoryEntry()
    note right of O: args: PendingAnalysis
    O -> H: saveAnalysisToHistory()
    note right of O: args: AnalysisHistoryEntry
    O -> ARS: call analysis results feature
    SRV -> WS: connection.close()
    WS -> ST: isBusy.set(false)
    ST -> F: emit(isBusy)
    note right of O: goto Clear Data

else Analysis Terminated

    alt User aborts
        F -> O: abortAnalysis()
        O -> WS: abort()    
        WS -> SRV: abort()

        alt Server confirms
            WS -> SRV: connection.close()
            WS -> ST: isBusy.set(false)
            ST -> F: emit(isBusy)
            O -> N: sendNotificationInfo()
            
        else Timeout
            WS -> SRV: connection.close()
            WS -> ST: isBusy.set(false)
            ST -> F: emit(isBusy)
            O -> N: sendNotificationWarning()
            O -> STG: deleteSessionId()
            STG -> SS: deleteSessionId()
            O -> L: unlockAnalysis(sessionId)
            note right of O: goto Start New Analysis
        end

    else Error
        SRV -> WS: connection.close()
        WS -> ST: isBusy.set(false)
        WS -> ST: error.set(...)
        ST -> F: emit(isBusy)
        ST -> F: emit(error)
        ST -> O: emit(error)
        O -> N: sendNotificationError()

        opt Connection Error
            alt With Retry
                F -> O: retryAnalysis()
                O -> ST: error.set(null)
                ST -> F: emit(error)
                O -> WS: reconnect(sessionId)
                WS -> SRV: reconnect(sessionId)
                WS -> ST: isBusy.set(true)
                ST -> F: emit(isBusy)
                note right of O: goto progress loop

            else Without Retry
                F -> O: cancelAnalysis()
                O -> N: sendNotificationInfo()
                O -> ST: error.set(null)
                ST -> F: emit(error)
            end
        end
    end

    note right of O: goto Clear Data
    note right of O: goto Try To Resume Analysis
    
end

@enduml