@startuml Continue Analysis

start

while (Connection exists?) is (yes)
    :Update progress;
endwhile (no)

if (Analysis successful?) then (yes)
    :Emit analysisResult;
    :Save analysisResult in history;
    :Show results;
    :Clear data;
    stop

else (no)
    switch (Termination reason)

    case (User abort)
        :Send abort request;

        if (Server confirms?) then (yes)
            :Show confirmation;        
        else (no)
            :Delete sessionId from sessionStorage;
            :Release lock;
            :Show warning;
            stop
        endif

    case (Error)
        :Notify user about the error;
            
        if (Connection error) then (yes)
            :Ask whether to retry analysis;

            if (Retry?) then (yes)
            :Delete error;
            :Continue analysis;
            stop
            endif
        endif
    endswitch
    
    :Clear data;
    :Try to resume analysis;
    stop
endif

@enduml