@startuml Start New Analysis

participant "Facade" as F
participant "Service" as S
participant "Lock Service" as LS
participant "Store Service" as STS
participant "Storage Service" as SGS
participant "Web Socket Service" as WSS
participant "Server" as SRV

database "SessionStorage" as SSG
database "LocalStorage" as LSG

F -> S: startNewAnalysis()
note right of F: args: AnalysisTargetFormModel
S -> S: generateSessionId()
S -> S: constructPendingAnalysis()
note right of S: args: AnalysisTargetFormModel
S -> LS: lock(sessionId)
S -> STS: pendingAnalysis.set()
note right of S: args: PendingAnalysis
S -> SGS: savePendingAnalysis()
note right of S: args: PendingAnalysis
SGS -> LSG: pendingAnalysis
S -> SGS: saveSessionId(sessionId)
SGS -> SSG: sessionId
S -> S: constructConnectionParams()
note right of S: args: PendingAnalysis
S -> WSS: connect(params)
WSS -> SRV: connect(params)
WSS -> STS: isBusy.set(true)
STS -> F: emit(isBusy)

@enduml