@startuml Try To Reconnect

participant "Facade" as F
participant "Service" as S
participant "Lock Service" as LS
participant "Store Service" as STS
participant "Storage Service" as SGS
participant "Web Socket Service" as WSS
participant "Server" as SRV

database "Session Storage" as SSG

note right of F: ngSnInit
F -> S: tryToReconnect()
S -> STS: read isBusy

alt isBusy = true
    note right of S: goto Continue Analysis

else isBusy = false
    S -> STS: resetState()
    S -> SGS: getSessionId()
    SGS -> S: sessionId

    alt sessionId does not exist
        note right of S: goto Try To Resume Analysis

    else sessionId exists
        S -> LS: lock(sessionId)
        LS -> S: acquired

        alt Lock unavailable
            S -> SGS: deleteSessionId()
            SGS -> SSG: deleteSessionId()
            note right of S: goto Try To Resume Analysis

        else Lock acquired
            S -> SGS: getPendingAnalyses()
            SGS -> S: pendingAnalyses

            alt sessionId not in pendingAnalyses
                S -> SGS: deleteSessionId()
                SGS -> SSG: deleteSessionId()
                S -> LS: unlock(sessionId)
                note right of S: goto Try To Resume Analysis

            else sessionId in pendingAnalyses
                S -> WSS: reconnect(sessionId)
                WSS -> SRV: reconnect(sessionId)
                WSS -> STS: isBusy.set(true)
                STS -> F: emit(isBusy)
                SRV -> WSS: progresss
                WSS -> STS: progress.set(...)
                STS -> F: emit(progress)
                note right of S: goto Continue Analysis
            end
        end
    end
end

@enduml