@startuml Try To Resume Analysis

participant "UI" as U
participant "Facade" as F
participant "Orchestrator" as O
participant "Lock Service" as L
participant "Notification Service" as N
participant "Store Service" as ST
participant "Storage Service" as STG
participant "Web Socket Service" as WS
participant "Server" as SRV

database "Session Storage" as SS
database "Local Storage" as LS

O -> STG: getPendingAnalyses()
STG -> O: pendingAnalyses

alt pendingAnalyses empty
    O -> ST: showModal.set(false)
    ST -> F: emit(showModal)
    F -> U: emit(showModal)
    note left of O: goto Start New Analysis

else pendingAnalyses exist
    loop Unprocessed pendingAnalysis?
        O -> L: lock(sessionId)
        L -> O: acquired

        opt Lock acquired
            O -> STG: getPendingAnalyses()
            STG -> O: pendingAnalyses
            
            alt Locked sessionId was deleted from pendingAnalyses
                O -> L: unlock(sessionId)

            else Locked sessionId still in pendingAnalyses
                O -> ST: showModal.set(true)
                ST -> F: emit(showModal)
                F -> U: emit(showModal)

                alt User wants to continue
                    U -> F: resumeAnalysis()
                    F -> O: resumeAnalysis()
                    O -> STG: saveSessionId(sessionId)
                    STG -> SS: sessionId
                    O -> WS: reconnect(sessionId)
                    WS -> SRV: reconnect(sessionId)
                    WS -> ST: isBusy.set(true)
                    ST -> F: emit(isBusy)
                    F -> U: emit(isBusy)
                    O -> ST: showModal.set(false)
                    ST -> F: emit(showModal)
                    F -> U: emit(showModal)
                    SRV -> WS: progresss
                    WS -> ST: progress.set(...)
                    ST -> F: emit(progress)
                    F -> U: emit(progress)
                    note left of O: goto Continue Analysis

                else User abandons analysis
                    U -> F: abandonAnalysis();
                    F -> O: abandonAnalysis();
                    O -> STG: deletePendingAnalysis(sessionId)
                    STG -> LS: deletePendingAnalysis(sessionId)
                    O -> L: unlockAnalysis(sessionId)
                    O -> N: sendMessageCancel()
                    O -> ST: resetAnalysisState()
                    ST -> F: emit(showModal)
                    F -> U: emit(showModal)
                end
            end
        end
    end

   note left of O: goto Start New Analysis
end

@enduml