@startuml Try To Resume Analysis

participant "Facade" as F
participant "Service" as S
participant "Lock Service" as LS
participant "Notifications Facade" as NS
participant "Store Service" as STS
participant "Storage Service" as SGS
participant "Web Socket Service" as WSS
participant "Server" as SRV

database "Session Storage" as SSG
database "Local Storage" as LSG

S -> SGS: getPendingAnalyses()
SGS -> S: pendingAnalyses

alt pendingAnalyses empty
    S -> STS: showModal.set(false)
    STS -> F: emit(showModal)
    note right of S: goto Start New Analysis

else pendingAnalyses exist
    loop Unprocessed pendingAnalysis?
        S -> LS: lock(sessionId)
        LS -> S: acquired

        opt Lock acquired
            S -> SGS: getPendingAnalyses()
            SGS -> S: pendingAnalyses
            
            alt Locked sessionId was deleted from pendingAnalyses
                S -> LS: unlock(sessionId)

            else Locked sessionId still in pendingAnalyses
                S -> STS: showModal.set(true)
                STS -> F: emit(showModal)

                alt User wants to continue
                    F -> S: resumeAnalysis()
                    S -> SGS: saveSessionId(sessionId)
                    SGS -> SSG: sessionId
                    S -> WSS: reconnect(sessionId)
                    WSS -> SRV: reconnect(sessionId)
                    WSS -> STS: isBusy.set(true)
                    STS -> F: emit(isBusy)
                    S -> STS: showModal.set(false)
                    STS -> F: emit(showModal)
                    SRV -> WSS: progresss
                    WSS -> STS: progress.set(...)
                    STS -> F: emit(progress)
                    note right of S: goto Continue Analysis

                else User abandons analysis
                    F -> S: abandonAnalysis();
                    S -> SGS: deletePendingAnalysis(sessionId)
                    SGS -> LSG: deletePendingAnalysis(sessionId)
                    S -> LS: unlockAnalysis(sessionId)
                    S -> NS: sendNotificationInfo()
                    S -> STS: resetAnalysisState()
                    note right of S: goto Try To Resume Analysis
                end
            end
        end
    end

   note right of S: goto Start New Analysis
end

@enduml