@startuml Startup Flow

start

if (isBusy?) then (yes)
    :Continue analysis;
    stop
endif

:Reset state;
:Read sessionId from sessionStorage;

if (sessionId exists?) then (no)
    :Try to resume analysis;
    stop
endif

:Read pendingAnalyses;

if (sessionId in pendingAnalyses?) then (no)
    :Delete sessionId from sessionStorage;
    :Try to resume analysis;
    stop
endif

:Query Web Locks;

if (Lock for sessionId exists?) then (yes)
    :Delete sessionId from sessionStorage;
    :Try to resume analysis;
    stop
endif

:Try to acquire lock;

if (Lock acquired?) then (yes)
    :Reconnect to sessionId;
    :Receive last status;
    :Continue analysis;
    stop
else (no)
    :Delete sessionId from sessionStorage;
    :Try to resume analysis;
    stop
endif

@enduml