@startuml Try To Reconnect

participant "UI" as U
participant "Facade" as F
participant "Orchestrator" as O
participant "Lock Service" as L
participant "Store Service" as ST
participant "Storage Service" as STG
participant "Web Socket Service" as WS
participant "Server" as SRV

database "Session Storage" as SS

note right of U: ngOnInit
U -> F: tryToReconnect()
F -> O: tryToReconnect()
O -> ST: read isBusy

alt isBusy = true
    note left of O: goto Continue Analysis

else isBusy = false
    O -> ST: resetState()
    O -> STG: getSessionId()
    STG -> O: sessionId

    alt sessionId does not exist
        note left of O: goto Try To Resume Analysis

    else sessionId exists
        O -> L: lock(sessionId)
        L -> O: acquired

        alt Lock unavailable
            O -> STG: deleteSessionId()
            STG -> SS: deleteSessionId()
            note left of O: goto Try To Resume Analysis

        else Lock acquired
            O -> STG: getPendingAnalyses()
            STG -> O: pendingAnalyses

            alt sessionId not in pendingAnalyses
                O -> STG: deleteSessionId()
                STG -> SS: deleteSessionId()
                O -> L: unlock(sessionId)
                note left of O: goto Try To Resume Analysis

            else sessionId in pendingAnalyses
                O -> WS: reconnect(sessionId)
                WS -> SRV: reconnect(sessionId)
                WS -> ST: isBusy.set(true)
                ST -> F: emit(isBusy)
                F -> U: emit(isBusy)
                SRV -> WS: progresss
                WS -> ST: progress.set(...)
                ST -> F: emit(progress)
                F -> U: emit(progress)
                note left of O: goto Continue Analysis
            end
        end
    end
end

@enduml