@startuml Continue Analysis

participant "Facade" as F
participant "Service" as S
participant "Lock Service" as LS
participant "Notification Service" as NS
participant "Analysis History Facade" as AHF
participant "Analysis Results Facade" as ARF
participant "Store Service" as STS
participant "Storage Service" as SGS
participant "Web Socket Service" as WSS
participant "Server" as SRV

loop Until closed
    SRV -> WSS: progress
    WSS -> STS: progress.set(...)
    STS -> F: emit(progress)
end

alt Analysis Successful
    SRV -> WSS: result
    WSS -> STS: result.set(analysisId)
    STS -> S: emit(result)
    S -> NS: sendNotificationSuccess()
    S -> S: constructAnalysisHistoryEntry()
    note right of S: args: PendingAnalysis
    S -> AHF: saveAnalysisToHistory()
    note right of S: args: AnalysisHistoryEntry
    S -> ARF: call analysis results facade
    SRV -> WSS: connection.close()
    WSS -> STS: isBusy.set(false)
    STS -> F: emit(isBusy)
    note right of S: goto Clear Data

else Analysis Terminated

    alt User aborts
        F -> S: abortAnalysis()
        S -> WSS: abort()    
        WSS -> SRV: abort()

        alt Server confirms
            WSS -> SRV: connection.close()
            WSS -> STS: isBusy.set(false)
            STS -> F: emit(isBusy)
            S -> NS: sendNotificationInfo()
            
        else Timeout
            WSS -> SRV: connection.close()
            WSS -> STS: isBusy.set(false)
            STS -> F: emit(isBusy)
            S -> NS: sendNotificationWarning()
            S -> SGS: deleteSessionId()
            SGS -> SS: deleteSessionId()
            S -> LS: unlockAnalysis(sessionId)
            note right of S: goto Start New Analysis
        end

    else Error
        SRV -> WSS: connection.close()
        WSS -> STS: isBusy.set(false)
        WSS -> STS: error.set(...)
        STS -> F: emit(isBusy)
        STS -> F: emit(error)
        STS -> S: emit(error)
        S -> NS: sendNotificationError()

        opt Connection Error
            alt With Retry
                F -> S: retryAnalysis()
                S -> STS: error.set(null)
                STS -> F: emit(error)
                S -> WSS: reconnect(sessionId)
                WSS -> SRV: reconnect(sessionId)
                WSS -> STS: isBusy.set(true)
                STS -> F: emit(isBusy)
                note right of S: goto progress loop

            else Without Retry
                F -> S: cancelAnalysis()
                S -> NS: sendNotificationInfo()
                S -> STS: error.set(null)
                STS -> F: emit(error)
            end
        end
    end

    note right of S: goto Clear Data
    note right of S: goto Try To Resume Analysis
    
end

@enduml