@startuml Try To Resume Analysis

start
:Read pendingAnalyses;

if (pendingAnalyses empty?) then (yes)
    :Start new analysis;
    stop
endif

while (Unprocessed pendingAnalysis?) is (yes)
    :Select analysis;
    :Try to acquire lock;

    if (Lock acquired?) then (yes)
        :Read pendingAnalyses;

        if (Locked sessionId still in pendingAnalyses?) then (no)
            :Release lock;

        else (yes)
            :Ask user whether to continue analysis;

            if (User wants to continue?) then (yes)
                :Save sessionId in sessionStorage;
                :Reconnect to sessionId;
                :Receive last status;
                :Continue analysis;
                stop

            else (no)
                :Delete pendingAnalysis from localStorage;
                :Release lock;
            endif
        endif
    endif
endwhile (no)

:Start new analysis;
stop

@enduml